2020-05-27 18:14:46,690 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNTkwNjI4NzEyLjEyNjYxNzJ9.dP8206b3iQMgRVTZl526rRFIK8Y_tyiewBS3Kb5lalc [POST] [in /Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/heliu/flask/microblog/app/routes.py", line 188, in reset_password
    user.set_password(form.form.password.data)
AttributeError: 'ResetPasswordForm' object has no attribute 'form'
2020-05-27 20:35:26,612 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNTkwNjM3NDg0LjcyNDIxODF9.Yw8GvgCOvXY6i4kpqPjoUZxZvXdkD8UrdcziHz1IUPo [POST] [in /Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/heliu/anaconda3/envs/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/heliu/flask/microblog/app/routes.py", line 188, in reset_password
    user.set_password(form.form.password.data)
AttributeError: 'ResetPasswordForm' object has no attribute 'form'
2020-05-28 10:44:48,593 INFO: Microblog startup [in /Users/heliu/flask/microblog/app/__init__.py:45]
